apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: site-template
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/votre-username/site-template.git'
    path: manifests
    targetRevision: main
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
